version: 0.2

phases:
  install:
    commands:
      - apt-get install curl
    finally:
      - echo Installing stuff finished
  build:
    commands:
      - echo Entered the build phase ...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/themes
      - curl -s -L https://github.com/gcushen/hugo-academic/archive/v4.3.1.zip -o academic.zip
      - unzip academic.zip
      - cd ..
      - hugo --quiet
    finally:
      - echo Building the HTML files finished
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/public/
discard-paths: no
